from chips_main import chips_main

chips_main(crispys_output_path="/groups/itay_mayrose/udiland/crispys_test/test_files_git/for_debug/drop_dup",
            crispys_output_name="HOM05D000177_3genes_basic",
            chips_output_name="chips",
            restriction_site="GGTCTC",
            genome_by_chr_path="/groups/itay_mayrose/udiland/crispys_chips_arabidopsis/ath_split_files",
            pam_file_path="/groups/itay_mayrose/udiland/crispys_chips_arabidopsis/pam",
            gff_file_path="/groups/itay_mayrose/udiland/crispys_chips_arabidopsis/annotation.all_transcripts.all_features.ath.gff3.gz",
            max_number_of_mismatches=4,
            lower_intersect_limit=10,
            upper_intersect_limit=20,
            number_of_groups=20,
            n_with_best_guide=5,
            n_sgrnas=2,
            threads=4,
            number_of_singletons=5,
            scoring_function="moff",
            min_sg_per_gene=4)

# chips_main(crispys_output_path="/groups/itay_mayrose/udiland/crispys_test/test_files_git/for_debug/HOM05D000177_3",
#             crispys_output_name="moff_0.15",
#             chips_output_name="chips_moff_0.15",
#             restriction_site="GGTCTC",
#             genome_by_chr_path="/groups/itay_mayrose/udiland/crispys_chips_arabidopsis/ath_split_files",
#             pam_file_path="/groups/itay_mayrose/udiland/crispys_chips_arabidopsis/pam",
#             gff_file_path="/groups/itay_mayrose/udiland/crispys_chips_arabidopsis/annotation.all_transcripts.all_features.ath.gff3.gz",
#             max_number_of_mismatches=4,
#             lower_intersect_limit=10,
#             upper_intersect_limit=20,
#             number_of_groups=20,
#             n_with_best_guide=5,
#             n_sgrnas=2,
#             threads=4,
#             number_of_singltones=5,
#             scoring_function="moff",
#             min_sg_per_gene=4)